from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from slowapi.errors import RateLimitExceeded
from sqlalchemy import text
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.config import settings
from app.db.session import engine
from app.logging_config import configure_logging, get_logger
from app.middleware import RequestIDMiddleware
from app.rate_limit import limiter
from app.routers import (
    auth,
    contributions,
    episode,
    hospitals,
    multimodal,
    predict,
    saved,
    schemes,
    treatments,
)

configure_logging()
log = get_logger("faircare.app")


def _db_ok() -> bool:
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True
    except Exception as exc:  # pragma: no cover - depends on live DB
        log.warning("db_healthcheck_failed", error=str(exc))
        return False


@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info(
        "startup",
        env=settings.app_env,
        version=settings.app_version,
        db_ok=_db_ok(),
        groq_enabled=settings.groq_enabled,
        cors_origins=settings.backend_cors_origins,
    )
    yield
    log.info("shutdown")


app = FastAPI(
    title="FairCare API",
    description=(
        "Rule-based cost estimation, hospital lookup, and scheme eligibility, "
        "now backed by Postgres. Multimodal helpers (bill-photo OCR, voice "
        "transcription) run on Groq and only structure user-supplied media — "
        "no cost figure or eligibility result is ever generated by an LLM."
    ),
    version=settings.app_version,
    lifespan=lifespan,
)

app.state.limiter = limiter
app.add_middleware(RequestIDMiddleware)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.backend_cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["X-Request-ID"],
)


def _request_id(request: Request) -> str:
    return getattr(request.state, "request_id", "-")


@app.exception_handler(RateLimitExceeded)
async def _rate_limited(request: Request, exc: RateLimitExceeded):
    return JSONResponse(
        status_code=429,
        content={
            "detail": f"Rate limit exceeded: {exc.detail}",
            "request_id": _request_id(request),
        },
    )


@app.exception_handler(RequestValidationError)
async def _validation_error(request: Request, exc: RequestValidationError):
    return JSONResponse(
        status_code=422,
        content={
            "detail": exc.errors(),
            "request_id": _request_id(request),
        },
    )


@app.exception_handler(StarletteHTTPException)
async def _http_error(request: Request, exc: StarletteHTTPException):
    return JSONResponse(
        status_code=exc.status_code,
        content={"detail": exc.detail, "request_id": _request_id(request)},
    )


@app.exception_handler(Exception)
async def _unhandled(request: Request, exc: Exception):
    log.exception("unhandled_exception", request_id=_request_id(request))
    return JSONResponse(
        status_code=500,
        content={
            "detail": "Internal server error.",
            "request_id": _request_id(request),
        },
    )


app.include_router(treatments.router)
app.include_router(predict.router)
app.include_router(hospitals.router)
app.include_router(schemes.router)
app.include_router(auth.router)
app.include_router(multimodal.router)
app.include_router(contributions.router)
app.include_router(saved.router)
app.include_router(episode.router)


@app.get("/api/health")
def health():
    ok = _db_ok()
    return {
        "status": "ok" if ok else "degraded",
        "db": "ok" if ok else "down",
        "version": settings.app_version,
        "groq_enabled": settings.groq_enabled,
    }


@app.get("/api/health/live")
def live():
    return {"status": "ok"}


@app.get("/api/health/ready")
def ready():
    if _db_ok():
        return {"status": "ok"}
    return JSONResponse(status_code=503, content={"status": "not-ready", "db": "down"})


@app.get("/")
def root():
    return {
        "service": "FairCare API",
        "docs": "/docs",
        "health": "/api/health",
    }
