from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.routers import treatments, predict, hospitals, schemes, auth

app = FastAPI(
    title="Healthcare Cost Predictor API",
    description=(
        "Rule-based cost estimation, hospital lookup, and scheme eligibility. "
        "No cost figure or eligibility result here is ever generated by an LLM — "
        "everything traces back to app/data/*.json (swap for a real DB later)."
    ),
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(treatments.router)
app.include_router(predict.router)
app.include_router(hospitals.router)
app.include_router(schemes.router)
app.include_router(auth.router)


@app.get("/api/health")
def health():
    return {"status": "ok"}


@app.get("/")
def root():
    return {
        "service": "Healthcare Cost Predictor API",
        "docs": "/docs",
        "health": "/api/health",
    }
