"""Plain-language explanation of an estimate our rule-based ``cost_service``
already produced.

The model is handed ONLY the numbers we computed (plus any OCR line items the
caller passes through) and is told, emphatically, not to invent or recompute any
figure. Same trust model as ``bill_analysis.py``: strict prompt + Pydantic
schema, no numeric post-scrub. It never sees our cost tables.
"""
from __future__ import annotations

import json

from pydantic import BaseModel, Field, ValidationError

from app.config import settings
from app.services.multimodal.groq_client import (
    GroqUnavailable,
    chat_text,
    parse_json_block,
)

DISCLAIMER = (
    "The wording below is generated by an AI model from the figures already "
    "calculated above. The rupee amounts themselves come from our sourced sample "
    "data, not the model. This is not medical or financial advice."
)

_LANG_NAME = {"en": "English", "hi": "Hindi"}

_PROMPT_TEMPLATE = """You are helping a patient in India understand a hospital cost estimate that has ALREADY been calculated for them. You are a plain-language explainer, not a calculator and not a doctor.

STRICT RULES:
- Do NOT invent, adjust, recompute, or introduce ANY rupee figure that is not in the data below.
- Do NOT give medical advice or opinions about whether treatment is needed.
- Do NOT claim to know real hospital prices; only describe the numbers given.
- Keep it short, calm, and practical.

ESTIMATE DATA (already computed, do not change):
- Treatment: {treatment_name}
- Location: {location_label}
- Hospital type: {hospital_type}
- Typical (average) cost: Rs. {cost_avg}
- Range: Rs. {cost_min} to Rs. {cost_max}
- Confidence: {confidence_label}
- Note about the data: {fallback_reason}
- How it was built: {factors}

BILL LINE ITEMS FROM THE USER'S PHOTO (OCR, may be empty):
{line_items}

Respond with a single JSON object, in {language}, with exactly these keys:
  "summary": string  (2-3 sentences: what the range means and how firm it is)
  "line_item_notes": array of objects {{"item": string, "note": string}}  (one per provided line item; say ONLY whether it is a large or small share of the typical cost above - no outside price claims. Empty array if there are no line items.)
  "questions_to_ask": array of up to 4 short strings the patient can ask the hospital billing desk
  "scheme_hint": string or null  (one general sentence, e.g. asking whether the hospital is PM-JAY/CGHS empanelled; null if nothing useful)
Output only the JSON object.
"""


class ExplanationLineItemNote(BaseModel):
    item: str = ""
    note: str = ""


class EstimateExplanation(BaseModel):
    summary: str
    line_item_notes: list[ExplanationLineItemNote] = Field(default_factory=list)
    questions_to_ask: list[str] = Field(default_factory=list)
    scheme_hint: str | None = None


def explain_estimate(
    *,
    treatment_name: str,
    location_label: str,
    hospital_type: str | None,
    our_estimate: dict,
    line_items: list[dict] | None,
    factors: list[dict] | None,
    lang: str = "en",
) -> dict:
    if not settings.groq_enabled:
        raise GroqUnavailable(
            "The estimate explainer is unavailable: no GROQ_API_KEY is configured."
        )

    language = _LANG_NAME.get(lang, "English")
    factor_text = (
        "; ".join(f"{f.get('label')}: {f.get('detail')}" for f in (factors or []))
        or "n/a"
    )
    li = [
        {"description": x.get("description", ""), "amount": x.get("amount")}
        for x in (line_items or [])
        if x.get("description") or x.get("amount") is not None
    ]
    prompt = _PROMPT_TEMPLATE.format(
        treatment_name=treatment_name,
        location_label=location_label or "not specified",
        hospital_type=hospital_type or "any",
        cost_avg=our_estimate["cost_avg"],
        cost_min=our_estimate["cost_min"],
        cost_max=our_estimate["cost_max"],
        confidence_label=our_estimate.get("confidence_label", "unknown"),
        fallback_reason=our_estimate.get("fallback_reason") or "none",
        factors=factor_text,
        line_items=json.dumps(li, ensure_ascii=False) if li else "[] (none)",
        language=language,
    )

    raw = chat_text(prompt=prompt)
    try:
        explanation = EstimateExplanation.model_validate(parse_json_block(raw))
    except (ValidationError, GroqUnavailable) as exc:
        raise GroqUnavailable(
            "The explainer could not produce a usable summary this time. "
            "Please try again."
        ) from exc

    return {**explanation.model_dump(), "disclaimer": DISCLAIMER}
